endroid_qr_code:
  default:
    writer: Endroid\QrCode\Writer\PngWriter
    size: 1000
    encoding: 'UTF-8'
    error_correction_level: 'high'
    round_block_size_mode: 'margin'
    foregroundColor: [ 36, 44, 127 ]
    logo_path: '%kernel.project_dir%/assets/api/images/jazz-logo-with-background.png'
    logo_resize_to_width: 337
    logo_punchout_background: false
    background_color: [ 255, 255, 255 ]
