name: 'Maintenance mode'
description: 'Toggle maintenance mode on remote server'
inputs:
  turn-on:
    description: "Turn on maintenance on true"
    required: true
    type: boolean
  remote-dir:
    description: "Direcotry in which the application is deployed"
    required: true
    type: string
  ssh-host:
    description: "Host of SSH-server"
    required: true
    type: string
  ssh-port:
    description: "Port of SSH-server"
    required: true
    type: string
  ssh-user:
    description: "User on SSH-server"
    required: true
    type: string
  ssh-password:
    description: "Password on SSH-server"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload maintenance trigger
      if: inputs.turn-on == 'true'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-user }}
        password: ${{ inputs.ssh-password }}
        port: ${{ inputs.ssh-port }}
        script: |
          cd ./${{ inputs.remote-dir }}
          touch ./public/maintenance.htm
          echo "${{ env.GITHUB_WORKFLOW }} >> ${{ env.GITHUB_ACTION }}" > ./public/maintenance.htm

    - name: Remove maintenance trigger
      if: inputs.turn-on != 'true'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-user }}
        password: ${{ inputs.ssh-password }}
        port: ${{ inputs.ssh-port }}
        script: |
          cd ./${{ inputs.remote-dir }}
          rm -f ./public/maintenance.htm