<?php declare(strict_types=1);

namespace Jazzfreunde\App\Event\Listener\Twig;

use Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\WebpackEncoreBundle\Event\RenderAssetTagEvent;

/**
 * Adds nonce attribute to tags generated by Webpack Encore.
 */
#[AsEventListener(RenderAssetTagEvent::class, method: 'onRenderAssetTag')]
final class EncoreNonceListener
{
    /**
     * @param ContentSecurityPolicyListener $cspListener
     */
    public function __construct(
        #[Autowire(service: 'nelmio_security.csp_listener')]
        private ContentSecurityPolicyListener $cspListener
    ) {
    }

    /**
     * Adds nonce attribute to tags.
     *
     * The value of nonce attribute will be hidden in dev tools
     * @see https://stackoverflow.com/questions/55670985/google-chrome-stripping-nonce-values-from-script-tags/55673767#55673767
     */
    public function onRenderAssetTag(RenderAssetTagEvent $event): void
    {
        if ($event->isScriptTag()) {
                $nonce = $this->getNonce('script');
                $event->setAttribute('nonce', $nonce);
        }

        if ($event->isLinkTag()) {
            $rel = $event->getAttributes()['rel'];

            if ('stylesheet' === $rel) {
                $nonce = $this->getNonce('style');
                $event->setAttribute('nonce', $nonce);
            }
        }
    }

    /**
     * Generates nonce.
     *
     * @param string $usage
     *
     * @return string
     */
    private function getNonce(string $usage): string
    {
        return $this->cspListener->getNonce($usage);
    }
}
