version: 1.0
deploy:
  bootstrap:
    excludes:
      - var/
      - tests/
      - node_modules/
      - assets/app/
      - .env.dev
      - .env.test
      - phpunit.xml
      - phpunit.xml.dist
      - psalm.xml
      - ruleset.xml
      - symfony.lock
      - composer.json
      - composer.lock
      - package.json
      - package-lock.json
      - postcss.config.js
      - tailwind.config.js
      - webpack.config.js
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - mkdir -p var && chmod -R o+w var
      - php8.2-cli bin/console cache:clear
  recurring:
    excludes:
      - var/
      - tests/
      - node_modules/
      - assets/app/
      - .env.dev
      - .env.test
      - phpunit.xml
      - phpunit.xml.dist
      - psalm.xml
      - ruleset.xml
      - symfony.lock
      - composer.json
      - composer.lock
      - package.json
      - package-lock.json
      - postcss.config.js
      - tailwind.config.js
      - webpack.config.js
    pre-deployment-remote-commands:
      - touch ./public/maintenance.htm
      - echo "deploy-now" > ./public/maintenance.htm
      - php8.2-cli bin/console messenger:stop-workers || true
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w var
      - rm -rf ./var/cache/*
      - php8.2-cli bin/console cache:clear --verbose
      - php8.2-cli bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
      - rm -f ./public/maintenance.htm
runtime:
  cron-jobs:
    - command: php8.2-cli $HOME/htdocs/bin/console messenger:consume async --time-limit=58
      schedule: "* * * * *"
    - command: php8.2-cli $HOME/htdocs/bin/console messenger:consume jobs --time-limit=60
      schedule: "0 0 * * *"