version: 1.0
deploy:
  bootstrap:
    excludes:
      - var/
      - tests/
      - node_modules/
      - .env.dev
      - .env.test
      - phpunit.xml
      - phpunit.xml.dist
      - psalm.xml
      - ruleset.xml
      - symfony.lock
      - composer.json
      - composer.lock
      - package.json
      - package-lock.json
      - postcss.config.js
      - tailwind.config.js
      - webpack.config.js
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - mkdir -p var && chmod -R o+w var
      - php8.2-cli bin/console cache:clear
  recurring:
    excludes:
      - var/
      - tests/
      - node_modules/
      - .env.dev
      - .env.test
      - phpunit.xml
      - phpunit.xml.dist
      - psalm.xml
      - ruleset.xml
      - symfony.lock
      - composer.json
      - composer.lock
      - package.json
      - package-lock.json
      - postcss.config.js
      - tailwind.config.js
      - webpack.config.js
    pre-deployment-remote-commands:
      - touch ./public/maintenance.htm
      - echo "deploy-now" > ./public/maintenance.htm
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w var
      - php8.2-cli bin/console cache:clear --verbose
      - php8.2-cli bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction --all-or-nothing
      - rm -f ./public/maintenance.htm
