# source code bindings
x-bind-source: &source
    type: bind
    source: ../..
    target: /usr/project

# cached dependencies
x-volume-shared-vendor: &vendor
    type: volume
    source: jazzfreunde-vendor
    target: /usr/project/api/vendor
x-volume-node_modules: &node_modules
    type: volume
    target: /usr/project/api/node_modules

# docker build.args
x-dev-buildargs: &dev-buildargs
    php_version: "8.2"
    project_dir: /usr/project
    phpini_path: .docker/php/php.ini-development
    xdebugini_path: .docker/php/dev-xdebug.ini
    xdebug_logdir: /usr/project/api/var/logs

services:
    jazzfreunde-dev-environment:
        container_name: jazzfreunde-dev-environment
        build:
            context: ..
            dockerfile: .docker/dev-cli.dockerfile
            args: *dev-buildargs
        volumes:
            - *source
            - *vendor
            - *node_modules
        environment:
            - APP_ENV=dev # Default Environment
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command: /bin/sh -c "while sleep 1000; do :; done"

    jazzfreunde-apache-server:
        container_name: jazzfreunde-php-apache
        build:
            context: ..
            dockerfile: .docker/apache.dockerfile
            args:
                php_version: "8.2"
                virtualhost_conf_dir: .docker/apache
                phpini_path: .docker/php/php.ini-development
                xdebugini_path: .docker/php/server-xdebug.ini
                xdebug_logdir: /usr/project/api/var/logs
                cache_dirs: /usr/project/api/var/cache
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
        depends_on:
            - jazzfreunde-database-server
        environment:
            - APACHE_DOCUMENT_ROOT=/usr/project/api
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - *source
            - *vendor
            - /usr/project/api/var/cache

    jazzfreunde-database-server:
        container_name: jazzfreunde-mysql-database
        image: mariadb:10.6

        command: --default-authentication-plugin=mysql_native_password
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: jazzfreunde-api
            MARIADB_USER: dbu_localdev
            MARIADB_PASSWORD: 6hdth6e#
        ports:
            - 3306:3306
        volumes:
            - type: volume
              source: jazzfreunde-mysql-data
              target: /var/lib/mysql
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3

    jazzfreunde-database-admin:
        container_name: jazzfreunde-mysql-admin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - jazzfreunde-database-server

        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
        environment:
            PMA_HOST: jazzfreunde-mysql-database
            PMA_USER: dbu_localdev
            PMA_PASSWORD: 6hdth6e#
        ports:
            - "81:80"

    ksp105-mail-server:
        container_name: jazzfreunde-mail-server
        image: maildev/maildev
        environment:
            MAILDEV_WEB_PORT: 80
            MAILDEV_SMTP_PORT: 587
            MAILDEV_INCOMING_USER: mailuser
            MAILDEV_INCOMING_PASS: UOgw71yamcyt829cwily
        ports:
            - 587:587
            - 82:80
volumes:
    jazzfreunde-mysql-data:
    jazzfreunde-vendor:
