openapi: 3.1.0
info:
  title: 'Jazzfreunde API'
  description: 'Data access for Jazzfreunde database'
  version: 1.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/events:
    get:
      operationId: api_events_get_collection
      tags:
        - Event
      responses:
        '200':
          description: 'Event collection'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
      summary: 'Retrieves the collection of Event resources.'
      description: 'Retrieves the collection of Event resources.'
      parameters:
        -
          name: page
          in: query
          description: 'The collection page number'
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
        -
          name: itemsPerPage
          in: query
          description: 'The number of items per page'
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 30
            minimum: 0
          style: form
          explode: false
          allowReserved: false
        -
          name: 'start[before]'
          in: query
          description: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: form
          explode: false
          allowReserved: false
        -
          name: 'start[strictly_before]'
          in: query
          description: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: form
          explode: false
          allowReserved: false
        -
          name: 'start[after]'
          in: query
          description: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: form
          explode: false
          allowReserved: false
        -
          name: 'start[strictly_after]'
          in: query
          description: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: form
          explode: false
          allowReserved: false
        -
          name: 'order[start]'
          in: query
          description: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
            default: asc
            enum:
              - asc
              - desc
          style: form
          explode: false
          allowReserved: false
      deprecated: false
  '/api/events/{id}':
    get:
      operationId: api_events_id_get
      tags:
        - Event
      responses:
        '200':
          description: 'Event resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
            text/html:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: 'Not found'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error.jsonld'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          links: {  }
      summary: 'Retrieves a Event resource.'
      description: 'Retrieves a Event resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Event identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
  '/api/event_locations/{id}':
    get:
      operationId: api_event_locations_id_get
      tags:
        - EventLocation
      responses:
        '200':
          description: 'EventLocation resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLocation'
            text/html:
              schema:
                $ref: '#/components/schemas/EventLocation'
        '404':
          description: 'Not found'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error.jsonld'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          links: {  }
      summary: 'Retrieves a EventLocation resource.'
      description: 'Retrieves a EventLocation resource.'
      parameters:
        -
          name: id
          in: path
          description: 'EventLocation identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
components:
  schemas:
    Error:
      type: object
      description: 'A representation of common errors.'
      deprecated: false
      properties:
        title:
          readOnly: true
          description: 'A short, human-readable summary of the problem.'
          type:
            - string
            - 'null'
        detail:
          readOnly: true
          description: 'A human-readable explanation specific to this occurrence of the problem.'
          type:
            - string
            - 'null'
        status:
          type: number
          example: 404
          default: 400
        instance:
          readOnly: true
          description: 'A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.'
          type:
            - string
            - 'null'
        type:
          readOnly: true
          description: 'A URI reference that identifies the problem type'
          type: string
    Error.jsonld:
      type: object
      description: 'A representation of common errors.'
      deprecated: false
      properties:
        title:
          readOnly: true
          description: 'A short, human-readable summary of the problem.'
          type:
            - string
            - 'null'
        detail:
          readOnly: true
          description: 'A human-readable explanation specific to this occurrence of the problem.'
          type:
            - string
            - 'null'
        status:
          type: number
          example: 404
          default: 400
        instance:
          readOnly: true
          description: 'A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.'
          type:
            - string
            - 'null'
        type:
          readOnly: true
          description: 'A URI reference that identifies the problem type'
          type: string
        description:
          readOnly: true
          type:
            - string
            - 'null'
    Event:
      type: object
      description: 'Terminierte Veranstaltung'
      deprecated: false
      properties:
        id:
          readOnly: true
          type: integer
        title:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        location:
          $ref: '#/components/schemas/EventLocation'
        subtitle:
          type:
            - string
            - 'null'
        link:
          type:
            - string
            - 'null'
        category:
          default: none
          example: none
          type: string
          enum:
            - none
            - session
            - jazztage
            - jazz-and-literature
      required:
        - title
        - start
        - end
        - location
        - category
    EventLocation:
      type: object
      description: ''
      deprecated: false
      properties:
        id:
          readOnly: true
          type: integer
        name:
          type: string
      required:
        - name
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags:
  -
    name: Event
    description: 'Terminierte Veranstaltung'
  -
    name: EventLocation
    description: 'Event locations'
webhooks: {  }
