api_platform:
  enable_re_doc: false
  mapping:
    paths:
      - '%kernel.project_dir%/app/Entity'
  swagger:
    versions: [3]
  formats:
    json:
      mime_types: ['application/json']
    html:
      mime_types: ['text/html']
