security:
  providers:
    users:
      entity:
        class: 'Jazzfreunde\App\Entity\Security\User'
        property: "uuid"
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: users
      login_link:
        check_route: security_login_check
        signature_properties: ["uuid"]
        check_post_only: true
        lifetime: 300
        max_uses: 1

      logout:
        path: security_logout
        target: home

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true
