twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/assets/mail': mailasset
        '%kernel.project_dir%/templates/markdown': markdown
        '%kernel.project_dir%/templates/components/layout': layout
        '%kernel.project_dir%/templates/pages': pages
        '%kernel.project_dir%/templates/email': email

    globals:
        github_repository: '%env(DEPLOYMENT_GITHUB_REPOSITORY)%'
        github_sha: '%env(DEPLOYMENT_GITHUB_SHA)%'
        github_sha_short: '%env(DEPLOYMENT_GITHUB_SHORT_SHA)%'
        newsletter_subscription_service: "@jazzfreunde.newsletter_subscription"

when@test:
    twig:
        strict_variables: true

when@dev:
    twig:
        strict_variables: true
