services:
    _defaults:
        autowire: true
        autoconfigure: true

    Jazzfreunde\App\Service\:
        resource: '../app/Service/'

    Jazzfreunde\App\Controller\:
        resource: '../app/Controller/'

    Jazzfreunde\App\Component\:
        resource: '%kernel.project_dir%/app/Component'

    Jazzfreunde\App\Component\LocalStorage\Share\SharedStorageComponent:
        factory: ['Jazzfreunde\App\Component\LocalStorage\Share\SharedStorageComponent', 'getSharedStorage']

    Jazzfreunde\App\Service\Content\LegacyStub:
        arguments:
        - '%kernel.project_dir%/legacy/pages'