services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $publicDir: '%kernel.project_dir%/public'

    Jazzfreunde\App\Service\:
        resource: '%kernel.project_dir%/app/Service/'

    Jazzfreunde\App\Controller\:
        resource: '%kernel.project_dir%/app/Controller/'

    Jazzfreunde\App\Event\:
        resource: '%kernel.project_dir%/app/Event/'
        exclude: '**/*Event'

    Jazzfreunde\App\Message\Handler\:
        resource: '%kernel.project_dir%/app/Message/Handler/'

    # register the service for twig to make createForm available in twig templates
    jazzfreunde.newsletter_subscription:
        class: Jazzfreunde\App\Service\Newsletter\NewsletterFormService

    Symfony\WebpackEncoreBundle\Asset\EntrypointLookupInterface:
        alias: webpack_encore.entrypoint_lookup[mail]
        public: true