version: '3.9'

services:
    apache-server:
        container_name: jazzfreunde-php-apache

        build:
            context: .
        environment:
            - APACHE_DOCUMENT_ROOT=/usr/project/src/public
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/usr/project:rw,cached
        secrets:
            - user_ssh_key
        extra_hosts:
            - "host.docker.internal:host-gateway"

    database-server:
        container_name: jazzfreunde-mysql-database
        image: mysql:latest

        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jazzfreunde-api
            MYSQL_USER: dbu_localdev
            MYSQL_PASSWORD: 6hdth6e#
        ports:
            - 3306:3306
        volumes:
            - mysql-data-jazzfreunde:/var/lib/mysql

    database-admin:
        container_name: jazzfreunde-mysql-admin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - database-server

        environment:
            PMA_HOST: jazzfreunde-mysql-database
            PMA_USER: dbu_localdev
            PMA_PASSWORD: 6hdth6e#
        ports:
          - "8081:80"
volumes:
    mysql-data-jazzfreunde:

secrets:
    user_ssh_key:
        file: ~/.ssh/id_ed25519