version: '3.9'

services:
    apache-server:
        container_name: jazzfreunde-php-apache

        build:
            context: .
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
            APACHE_DOCUMENT_ROOT: /usr/project/src/public
        ports:
            - "8080:80"
        volumes:
            - ../:/usr/project/
        secrets:
            - user_ssh_key
    database-server:
        container_name: jazzfreunde-mysql-database
        image: mysql:latest

        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jazzfreunde-api
            MYSQL_USER: dbu_localdev
            MYSQL_PASSWORD: 6hdth6e#
        ports:
            - 3306:3306
        volumes:
            - mysql-data-jazzfreunde:/var/lib/mysql
    database-admin:
        container_name: jazzfreunde-mysql-admin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - database-server

        environment:
            PMA_HOST: jazzfreunde-mysql-database
            PMA_USER: dbu_localdev
            PMA_PASSWORD: 6hdth6e#
        ports:
          - "8081:80"
volumes:
    mysql-data-jazzfreunde:

secrets:
    user_ssh_key:
        file: ~/.ssh/id_ed25519