/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Event resources.
         * @description Retrieves the collection of Event resources.
         */
        get: operations["api_events_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Event resource.
         * @description Retrieves a Event resource.
         */
        get: operations["api_events_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event_locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a EventLocation resource.
         * @description Retrieves a EventLocation resource.
         */
        get: operations["api_event_locations_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Terminierte Veranstaltung */
        Event: {
            readonly id?: number;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location: components["schemas"]["EventLocation"];
            subtitle?: string | null;
            link?: string | null;
            /**
             * @default none
             * @example none
             * @enum {string}
             */
            category: "none" | "session" | "jazztage";
        };
        EventLocation: {
            readonly id?: number;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_events_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                "start[before]"?: string;
                "start[strictly_before]"?: string;
                "start[after]"?: string;
                "start[strictly_after]"?: string;
                "order[start]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                    "text/html": components["schemas"]["Event"][];
                };
            };
        };
    };
    api_events_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                    "text/html": components["schemas"]["Event"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_event_locations_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description EventLocation identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EventLocation resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventLocation"];
                    "text/html": components["schemas"]["EventLocation"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
