[XDebug]
zend_extension=xdebug.so

; https://xdebug.org/docs/
xdebug.mode = debug

; https://github.com/mac-cain13/xdebug-helper-for-chrome
xdebug.start_with_request=trigger
; xdebug.trigger_value=

xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=VSCODE
xdebug.max_nesting_level=1000

xdebug.log_level=3
xdebug.log=/usr/project/src/logs/xdebug.log