name: Create new draft from tag for a subsequent release
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  draft-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Create new draft
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "prod-app-artifact.zip,prod-vendor-artifact.zip"
          body: ${{steps.github_release.outputs.changelog}}
