name: Build frontend application
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Rerence name of the artifact produced"
        required: true
        type: string
      environment:
        description: "The environment in which to build the app"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      # Check out branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Install Composer packages
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-scripts

      # Install Composer packages
      - name: Install assets
        run: |
          echo "DATABASE_URL=dummy" > .env.local
          chmod +x bin/console
          bin/console assets:install --env=${{ inputs.environment }}

      - name: Build Encore files
        run: encore ${{ inputs.environment == 'prod' && 'production --progress' || 'dev'}}

      # Upload app artifact
      - uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifact-name }}
          path: src/public/
