name: Build frontend application
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Rerence name of the artifact produced"
        required: true
        type: string
      environment:
        description: "The environment in which to build the app"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.x

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-scripts

      - name: Install npm dependencies
        run: npm install

      - name: Install assets
        run: |
          echo "DATABASE_URL=dummy" > .env.local
          chmod +x bin/console
          bin/console assets:install --env=${{ inputs.environment }}

      - name: Build Encore files
        run: |
          npm run ${{ inputs.environment == 'prod' && 'build-prod-app' || 'build-dev-app'}}
          npm run ${{ inputs.environment == 'prod' && 'build-prod-mail' || 'build-dev-mail'}}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: src/public/
