# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./src

jobs:
  build-vendor-libraries:
    defaults:
      run:
        working-directory: ./src
    uses: jazzfreunde-ingolstadt/homepage-php/.github/workflows/compose-vendor.yml@master
    with:
      artifact-name: stage-vendor-artifact

  build-app:
    defaults:
      run:
        working-directory: ./src
    uses: jazzfreunde-ingolstadt/homepage-php/.github/workflows/build-application.yml@master
    with:
      artifact-name: stage-app-artifact
      environment: stage

# Please do not rename this job
  build-project:
    name: build homepage-php
    runs-on: ubuntu-latest
    needs: [ build-vendor-libraries, build-app ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Download Composer artifact
        uses: actions/download-artifact@v3
        with:
          name: stage-vendor-artifact
          path: src/vendor

      - name: Download Encore artifact
        uses: actions/download-artifact@v3
        with:
          name: stage-app-artifact
          path: src/public

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 89819d12-f5c7-4de6-bf5c-5bda215d7b2c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/homepage-php/config.yaml
          action: upload
