name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: src

jobs:
  build-vendor-libraries:
    uses: ./.github/workflows/compose-vendor.yml
    with:
      artifact-name: prod-vendor-artifact

  build-app:
    uses: ./.github/workflows/build-application.yml
    with:
      artifact-name: prod-app-artifact
      environment: prod

  build-project:
    name: build homepage-php
    runs-on: ubuntu-latest
    needs: [ build-vendor-libraries, build-app ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Download Composer artifact
        uses: actions/download-artifact@v4
        with:
          name: prod-vendor-artifact
          path: src/vendor

      - name: Download Encore artifact
        uses: actions/download-artifact@v4
        with:
          name: prod-app-artifact
          path: src/public

      - name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          input-directory: .deploy-now/homepage-php
          output-directory: ${{ env.DEPLOYMENT_FOLDER }}
          intermediate-data-file: ${{ env.DEPLOYMENT_FOLDER }}/.template-renderer-data

      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: b231b1a4-4e91-456e-a36d-5c432505082c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/homepage-php/config.yaml
          action: upload
