name: Publish Deploy
on:
  push:
    tags:
      - v*
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      # Check out branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      # Install Composer
      #- name: Install Composer Dependencies
      #  run: composer install --prefer-dist --no-progress
      
      # Deploy to ftp server
      - name: sFTP Deploy (Publish)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.PUBLISH_FTP_SERVER }}
          ftp-username: ${{ secrets.PUBLISH_FTP_USER }}
          ftp-password: ${{ secrets.PUBLISH_FTP_PASSWORD }}
          local-dir: src/
          git-ftp-args: --insecure
