name: Staging Deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**.code-workspace'
      - '.devcontainer/**'
      - '.env*'
      - '**.gitignore'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
        
    steps:
      # Check out branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      # Install Composer packages
      - name: Install Composer Dependencies
        run: chmod +x bin/console && composer install --prefer-dist --no-dev --optimize-autoloader
        
      # Store vendor packages
      - uses: actions/upload-artifact@main
        with:
          name: composer artifacts
          path: src/vendor/
          
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    needs: build
    
    steps:
      # Check out branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      # Get built composer packages
      - uses: actions/download-artifact@main
        with:
          name: composer artifacts
          path: src/vendor
        
      # Prepare Console
      - name: Grant rights to console
        run: chmod +x bin/console
        
      # Decrypt secrets
      - name: Generate deployable .env
        run: php bin/console secrets:decrypt-to-local --force --env=stage
        env:
          SYMFONY_DECRYPTION_SECRET: ${{ secrets.SYMFONY_STAGE_DECRYPT_PRIVATE }}
          
      # Symfony tasks
      - name: Prepare environment config
        run: mv .env.stage.local .env.local
        
      - name: Finalize symfony rollout
        run: git checkout bin/console
    
      # Deploy to ftp server
      - name: sFTP Deploy (Staging)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.STAGING_FTP_SERVER }}
          ftp-username: ${{ secrets.STAGING_FTP_USER }}
          ftp-password: ${{ secrets.STAGING_FTP_PASSWORD }}
          local-dir: src
          git-ftp-args: --insecure
          
  config:
    runs-on: ubuntu-latest
    needs: push
    
    steps:
    - name: Prepare server environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CROSS_ENV_SSH_HOST }}
        username: ${{ secrets.CROSS_ENV_SSH_USER }}
        password: ${{ secrets.CROSS_ENV_SSH_PASSWORD }}
        port: ${{ secrets.CROSS_ENV_SSH_PORT }}
        script: |
          cd ./stage
          chmod +x bin/console
          php bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction --no-debug
          php bin/console cache:clear
