name: Deploy to stage environment
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-vendor-libraries:
    uses: jazzfreunde-ingolstadt/homepage-php/.github/workflows/compose-vendor.yml@master
    with:
      artifact-name: stage-vendor-artifact

  build-app:
    uses: jazzfreunde-ingolstadt/homepage-php/.github/workflows/build-application.yml@master
    with:
      artifact-name: stage-app-artifact
      environment: stage

  delpoy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    needs: [build-vendor-libraries, build-app]

    steps:
      # Check out branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Get all atrifacts
      - uses: actions/download-artifact@v3
        with:
          name: stage-vendor-artifact
          path: src/vendor

      - uses: actions/download-artifact@v3
        with:
          name: stage-app-artifact
          path: src/public

      # Configure symfony environment
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: "v"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Generate deployable .env
        run: |
          chmod +x bin/console
          echo "APP_ENV=stage" > .env.stage.local
          echo "APP_VERSION=${{ steps.version.outputs.full }}" >> .env.stage.local
          php bin/console secrets:decrypt-to-local --force --env=stage
        env:
          SYMFONY_DECRYPTION_SECRET: ${{ secrets.SYMFONY_STAGE_DECRYPT_PRIVATE }}

      - name: Prepare environment config
        run: mv .env.stage.local .env.local

      # Reset tree for ftp-deploy
      - name: Finalize symfony rollout
        run: git checkout bin/console

      # Deploy to ftp server
      - name: Turn on maintenance mode
        uses: jazzfreunde-ingolstadt/homepage-php/.github/actions/toggle-maintenance-mode@master
        with:
          turn-on: true
          remote-dir: stage
          ssh-host: ${{ secrets.CROSS_ENV_SSH_HOST }}
          ssh-port: ${{ secrets.CROSS_ENV_SSH_PORT }}
          ssh-user: ${{ secrets.CROSS_ENV_SSH_USER }}
          ssh-password: ${{ secrets.CROSS_ENV_SSH_PASSWORD }}

      - name: sFTP Deploy (Staging)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.STAGING_FTP_SERVER }}
          ftp-username: ${{ secrets.STAGING_FTP_USER }}
          ftp-password: ${{ secrets.STAGING_FTP_PASSWORD }}
          local-dir: src
          git-ftp-args: --insecure

  warm-up:
    uses: jazzfreunde-ingolstadt/homepage-php/.github/workflows/warmpup-server.yml@master
    with:
      php-cli: php8.1-cli
      remote-dir: stage
    secrets: inherit
    needs: delpoy

  finalize:
    if: always()
    runs-on: ubuntu-latest
    needs: warm-up

    steps:
      - uses: jazzfreunde-ingolstadt/homepage-php/.github/actions/toggle-maintenance-mode@master
        with:
          turn-on: false
          remote-dir: stage
          ssh-host: ${{ secrets.CROSS_ENV_SSH_HOST }}
          ssh-port: ${{ secrets.CROSS_ENV_SSH_PORT }}
          ssh-user: ${{ secrets.CROSS_ENV_SSH_USER }}
          ssh-password: ${{ secrets.CROSS_ENV_SSH_PASSWORD }}