name: Staging Deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**.code-workspace'
      - '.devcontainer/**'
      - '.env'
      - '**.gitignore'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
        
    steps:
      # Check out branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      # Install Composer packages
      - name: Install Composer Dependencies
        run: chmod +x bin/console && composer install --prefer-dist --no-dev --optimize-autoloader
        
      # Store vendor packages
      - uses: actions/upload-artifact@main
        with:
          name: composer artifacts
          path: src/vendor/
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    needs: build
    
    steps:
      # Check out branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          
      # Get built composer packages
      - uses: actions/download-artifact@main
        with:
          name: composer artifacts
          path: src/vendor
        
      # Decrypt secrets
      - name: Generate deployable .env
        run: chmod +x bin/console && php bin/console secrets:decrypt-to-local --force --env=test
        env:
          SYMFONY_DECRYPTION_SECRET: ${{ secrets.SYMFONY_TEST_DECRYPT_PRIVATE }}

      - name: Prepare environment config
        run: mv .env.test.local .env.local
        
      # Configure and warm up cache
      - name: Configure app
        run: bin/console cache:clear --env=test
    
      # Deploy to ftp server
      - name: sFTP Deploy (Staging)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.STAGING_FTP_SERVER }}
          ftp-username: ${{ secrets.STAGING_FTP_USER }}
          ftp-password: ${{ secrets.STAGING_FTP_PASSWORD }}
          local-dir: src
          git-ftp-args: --insecure
