name: Toggle maintenance mode on remote server
on:
  workflow_call:
    inputs:
      turn-on:
        description: "Turn on maintenance on true"
        required: true
        type: boolean
      remote-dir:
        description: "Direcotry in which the application is deployed."
        required: true
        type: string

jobs:
  turn-on:
    if: inputs.turn-on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - name: Upload maintenance trigger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CROSS_ENV_SSH_HOST }}
          username: ${{ secrets.CROSS_ENV_SSH_USER }}
          password: ${{ secrets.CROSS_ENV_SSH_PASSWORD }}
          port: ${{ secrets.CROSS_ENV_SSH_PORT }}
          script: |
            cd ./${{ inputs.remote-dir }}
            touch ./public/maintenance.htm

  turn-off:
    if: !inputs.turn-on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - name: Remove maintenance trigger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CROSS_ENV_SSH_HOST }}
          username: ${{ secrets.CROSS_ENV_SSH_USER }}
          password: ${{ secrets.CROSS_ENV_SSH_PASSWORD }}
          port: ${{ secrets.CROSS_ENV_SSH_PORT }}
          script: |
            cd ./${{ inputs.remote-dir }}
            rm ./public/maintenance.htm
