name: Warmup server
on:
  workflow_call:
    inputs:
      php-cli:
        description: 'Name of the php-cli used'
        required: true
        type: string
      remote-dir:
        description: 'Direcotry in which the application is deployed.'
        required: true
        type: string
    
jobs:
  warm-up:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare server environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CROSS_ENV_SSH_HOST }}
        username: ${{ secrets.CROSS_ENV_SSH_USER }}
        password: ${{ secrets.CROSS_ENV_SSH_PASSWORD }}
        port: ${{ secrets.CROSS_ENV_SSH_PORT }}
        script: |
          cd ./${{ inputs.remote-dir }}
          chmod +x bin/console
          ${{ inputs.php-cli }} bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction --no-debug
          ${{ inputs.php-cli }} bin/console cache:clear